---
# http://about.travis-ci.org/docs/user/getting-started/

rvm:
  - 1.8.7
  - 1.9.3

before_script:
  - "bundle install"

script:
  - "rake spec"

# http://about.travis-ci.org/docs/user/build-configuration/#Set-environment-variables
env:
  - PUPPET_VERSION=3.2.1  HIERA_SPEC_GEM=hiera-puppet-helper HIERA_SPEC_GEM_VERSION=1.0.1
  - PUPPET_VERSION=3.2.1  HIERA_SPEC_GEM=rspec-hiera-puppet HIERA_SPEC_GEM_VERSION=1.0.0
  - PUPPET_VERSION=2.7.21 HIERA_SPEC_GEM=rspec-hiera-puppet HIERA_SPEC_GEM_VERSION=0.3.0

matrix:
  allow_failures:
    - env:
      - PUPPET_VERSION=2.7.21

# http://about.travis-ci.org/docs/user/notifications/#Email-notifications
notifications:
  email: false
